### ISSUE TITLE
Haxe conditionals cause any code after them to be greyed out

### ISSUE THREAD

**Issue by Gama11** [JoeRobich/fd-editorminimap#1]
![](http://i.imgur.com/46qx0Wh.png)

Tested on the latest FD dev branch build.

**Comment by flerokoo** [comment]
Same problem here (FlashDevelop 5)
Was it fixed for FD4.x?

![image](https://cloud.githubusercontent.com/assets/6369045/7898290/0ca51a2e-0704-11e5-8e4e-ee764f69e74e.png)
